In [64]:
import pandas as pd
import numpy as np
import random

In [50]:
df=pd.read_csv('Dry_Bean_Dataset.csv')
df

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0      28395    610.291       208.178117       173.888747      1.197191   
1      28734    638.018       200.524796       182.734419      1.097356   
2      29380    624.110       212.826130       175.931143      1.209713   
3      30008    645.884       210.557999       182.516516      1.153638   
4      30140    620.134       201.847882       190.279279      1.060798   
...      ...        ...              ...              ...           ...   
13606  42097    759.696       288.721612       185.944705      1.552728   
13607  42101    757.499       281.576392       190.713136      1.476439   
13608  42139    759.321       281.539928       191.187979      1.472582   
13609  42147    763.779       283.382636       190.275731      1.489326   
13610  42159    772.237       295.142741       182.204716      1.619841   

       Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0          0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1          0.411785       29172     191.272751  0.783968  0.984986   0.887034   
2          0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3          0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4          0.333680       30417     195.896503  0.773098  0.990893   0.984877   
...             ...         ...            ...       ...       ...        ...   
13606      0.765002       42508     231.515799  0.714574  0.990331   0.916603   
13607      0.735702       42494     231.526798  0.799943  0.990752   0.922015   
13608      0.734065       42569     231.631261  0.729932  0.989899   0.918424   
13609      0.741055       42667     231.653247  0.705389  0.987813   0.907906   
13610      0.786693       42600     231.686223  0.788962  0.989648   0.888380   

       Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  \
0         0.913358      0.007332      0.003147      0.834222      0.998724   
1         0.953861      0.006979      0.003564      0.909851      0.998430   
2         0.908774      0.007244      0.003048      0.825871      0.999066   
3         0.928329      0.007017      0.003215      0.861794      0.994199   
4         0.970516      0.006697      0.003665      0.941900      0.999166   
...            ...           ...           ...           ...           ...   
13606     0.801865      0.006858      0.001749      0.642988      0.998385   
13607     0.822252      0.006688      0.001886      0.676099      0.998219   
13608     0.822730      0.006681      0.001888      0.676884      0.996767   
13609     0.817457      0.006724      0.001852      0.668237      0.995222   
13610     0.784997      0.007001      0.001640      0.616221      0.998180   

          Class  
0         SEKER  
1         SEKER  
2         SEKER  
3         SEKER  
4         SEKER  
...         ...  
13606  DERMASON  
13607  DERMASON  
13608  DERMASON  
13609  DERMASON  
13610  DERMASON  

[13611 rows x 17 columns]

In [51]:

# Import label encoder 
from sklearn import preprocessing 
  
# label_encoder object knows  
# how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'species'. 
df['Class']= label_encoder.fit_transform(df['Class']) 
  
df['Class'].unique() 

array([5, 0, 1, 2, 4, 6, 3])

In [52]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [53]:
y

0        5
1        5
2        5
3        5
4        5
        ..
13606    3
13607    3
13608    3
13609    3
13610    3
Name: Class, Length: 13611, dtype: int32

In [90]:
from sklearn.model_selection import train_test_split,RandomizedSearchCV
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [65]:
new_df=pd.concat([X_train,y_train],axis=1)

In [66]:
new_df

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
10704  27490    618.868       233.001523       151.202562      1.540989   
13145  37946    738.476       264.960115       182.588263      1.451134   
2571   67686   1044.470       368.601069       234.202503      1.573856   
4683   74759   1058.713       405.850888       238.557776      1.701269   
12624  35110    693.189       254.183543       176.478601      1.440308   
...      ...        ...              ...              ...           ...   
13123  37832    720.476       263.034496       183.384981      1.434330   
3264   85890   1152.016       417.536420       262.719645      1.589285   
9845   51131    842.796       316.185621       207.028992      1.527253   
10799  27884    630.303       239.405409       148.484842      1.612322   
2732   70344   1037.985       378.651095       237.909773      1.591574   

       Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
10704      0.760845       27753     187.086491  0.731117  0.990524   0.901963   
13145      0.724651       38540     219.805250  0.759224  0.984587   0.874386   
2571       0.772198       69063     293.565141  0.708383  0.980062   0.779681   
4683       0.809009       76604     308.522471  0.751037  0.975915   0.838141   
12624      0.719690       35528     211.431881  0.765925  0.988235   0.918200   
...             ...         ...            ...       ...       ...        ...   
13123      0.716887       38289     219.474824  0.725168  0.988064   0.915862   
3264       0.777232       87188     330.694035  0.714654  0.985113   0.813271   
9845       0.755828       51654     255.150958  0.812506  0.989875   0.904585   
10799      0.784425       28196     188.422428  0.758253  0.988935   0.881995   
2732       0.777964       71521     299.273725  0.821354  0.983543   0.820455   

       Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  \
10704     0.802941      0.008476      0.002173      0.644714      0.993498   
13145     0.829579      0.006983      0.002040      0.688201      0.998672   
2571      0.796431      0.005446      0.001352      0.634302      0.998299   
4683      0.760187      0.005429      0.001118      0.577884      0.983136   
12624     0.831808      0.007240      0.002138      0.691904      0.996555   
...            ...           ...           ...           ...           ...   
13123     0.834396      0.006953      0.002079      0.696216      0.998603   
3264      0.792012      0.004861      0.001180      0.627284      0.996933   
9845      0.806966      0.006184      0.001618      0.651194      0.994537   
10799     0.787043      0.008586      0.002032      0.619437      0.998732   
2732      0.790368      0.005383      0.001296      0.624682      0.994227   

       Class  
10704      3  
13145      3  
2571       0  
4683       2  
12624      3  
...      ...  
13123      3  
3264       0  
9845       6  
10799      3  
2732       0  

[9527 rows x 17 columns]

In [85]:
s0 = new_df.sample(n = 900) 
s1 = new_df.sample(n = 900) 
s2 = new_df.sample(n = 900) 
s3 = new_df.sample(n = 900) 
s4 = new_df.sample(n = 900) 
s5 = new_df.sample(n = 900) 
s6 = new_df.sample(n = 900) 
s7 = new_df.sample(n = 900) 
s8 = new_df.sample(n = 900) 
s9 = new_df.sample(n = 900) 

In [97]:
s0_train = s0.iloc[:, :-1]
s0_test = s0.iloc[:, -1]

s1_train = s1.iloc[:, :-1]
s1_test = s1.iloc[:, -1]

s2_train = s2.iloc[:, :-1]
s2_test = s2.iloc[:, -1]

s3_train = s3.iloc[:, :-1]
s3_test = s3.iloc[:, -1]

s4_train = s4.iloc[:, :-1]
s4_test = s4.iloc[:, -1]

s5_train = s5.iloc[:, :-1]
s5_test = s5.iloc[:, -1]

s6_train = s6.iloc[:, :-1]
s6_test = s6.iloc[:, -1]

s7_train = s7.iloc[:, :-1]
s7_test = s7.iloc[:, -1]

s8_train = s8.iloc[:, :-1]
s8_test = s8.iloc[:, -1]

s9_train = s9.iloc[:, :-1]
s9_test = s9.iloc[:, -1]



In [ ]:
s1

In [89]:
from sklearn.svm import SVC
classifier = SVC()

In [100]:
param_dist = {"kernel": ["linear","poly","rbf"], 
    "C": [1,2,3], 
    "degree": [1,2] 
    }
random_search = RandomizedSearchCV(classifier,param_distributions=param_dist,n_iter=10,scoring='accuracy') 
random_search.fit(s1_train, s1_test)
print('Best Score: %s' % random_search.best_score_)
print('Best Hyperparameters: %s' % random_search.best_params_)

KeyboardInterrupt: 

In [ ]:
classifier.fit(X_train,y_train)

In [62]:
y_pred = classifier.predict(X_test)

In [63]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[337   0  32   0   3   4  13]
 [  0 133   1   0   0   0   0]
 [ 12   0 473   0   9   2   5]
 [  0   0   0 993   1  15  48]
 [  0   0  11   5 563   0  15]
 [  8   0   0   3   0 541  27]
 [  1   0   3  91  17  10 708]]


0.9177277179236043